# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
  - main

pool:
      vmImage: 'ubuntu-latest'
 
variables: 
  ImageRepository: 'shopping-backend'
  dockerfilepath: 'backend/Dockerfile'
  tag: '$(Build.BuildId)'

  stages:
    stage: Build
    displayName: 'Build Stage'

    jobs: 
      - job: BuildJob
        displayName: 'Verify Build Agent'

        steps:
        - checkout: self
        
        - scripts: |
              echo "Current Directory"
              pwd

              echo "Repository Files"
              ls -la

              echo "Docker-Version"
              docker --version

              echo "Docker-Compose-Version"
              docker-compose --version
          displayName: 'Verify Build Agent'




