trigger:
- main

pool:
  vmImage: 'ubuntu-latest'

variables:
  imageRepository: 'shopping-backend'
  dockerfilePath: 'backend/Dockerfile'
  tag: '$(Build.BuildId)'

stages:
- stage: Build
  displayName: 'Build Stage'

  jobs:
  - job: BuildJob
    displayName: 'Build Job'

    steps:
    - checkout: self

    - script: |
        echo "Current Directory:"
        pwd

        echo "Repository Files:"
        ls -la

        echo "Docker Version:"
        docker --version

        echo "Node Version:"
        node --version

        echo "NPM Version:"
        npm --version
      displayName: 'Verify Build Agent'

    - script: |
        cd backend
        npm install
      displayName: 'Install Dependencies'


    - script: |
        cd backend/Dockerfile
        docker build -t $(imageRepository):$(tag) -f $(dockerfilePath)
      displayName: 'Build Docker Image'

    - script: |
        docker images
      displayName: 'List Docker Images'

    - task: Docker@2
      displayName: 'Login to Azure Container Registry'
      inputs:
        command: login
        containerRegistry: 'Dockerconnection'

    - task: Docker@2
      displayName: 'Push Image'
      inputs:
        command: push
        repository: '$(imageRepository)'
        containerRegistry: 'Dockerconnection'
        tags: |
          $(tag)
          latest